### ISSUE TITLE
Crash in BugsnagClient.m

### ISSUE THREAD

**Issue by sethfri** [bugsnag/bugsnag-cocoa#845]
### Describe the bug
We're seeing a crash of unknown origin in BugsnagClient.m. This has affected 7 of our customers a total of 7 times, so it's fairly rare.

### Steps to reproduce
Unknown

### Environment
* Bugsnag version: 6.1.3
* CocoaPods version: 1.9.3
* Carthage version (if any): n/a
* iOS/tvOS/macOS version(s): 13.7.0, 14.0.1
* Simulator or physical device: iPhone 6s, iPhone XR
* XCode version: 6.2.1
* Swift version (if applicable): 5.1

### Stack Trace

<details><summary>Stack trace:</summary>

```
Crashed: MyQueue
0  libobjc.A.dylib                0x19698d9bc objc_retain + 76
1  CoreFoundation                 0x196c89ff0 __NSArrayI_new + 200
2  CoreFoundation                 0x196b2a4b4 -[NSArray initWithArray:range:copyItems:] + 412
3  CoreFoundation                 0x196b2e8f4 +[NSArray arrayWithArray:] + 72
4  MyApp                           0x103928dec -[BugsnagClient notify:handledState:block:] + 1003 (BugsnagClient.m:1003)
5  MyApp                           0x1039281a0 -[BugsnagClient notifyError:block:] + 882 (BugsnagClient.m:882)
6  MyApp                           0x10392063c +[Bugsnag notifyError:block:] + 136 (Bugsnag.m:136)
7  MyApp                           0x1043e4a68 specialized BugsnagLogStoreWriter.write(level:message:parameters:) + 4330752616 (<compiler-generated>:4330752616)
8  MyApp                           0x1043d76b8 AggregateLogStoreWriter.write(level:message:parameters:) + 4330698424 (<compiler-generated>:4330698424)
9  MyApp                           0x1043d7778 protocol witness for LogStoreWriter.write(level:message:parameters:) in conformance AggregateLogStoreWriter + 4330698616 (<compiler-generated>:4330698616)
10 MyApp                           0x1043dde30 Logger.log(level:_:parameters:) + 4330724912 (<compiler-generated>:4330724912)
11 MyApp                           0x1042b5974 closure #1 in RedactedType1.redactedMethod + 4329511284 (<compiler-generated>:4329511284)
12 MyApp                           0x1045b1e50 RedactedType3.redactedMethod + 318 (RedactedType3.swift:318)
13 MyApp                           0x1033aff98 protocol witness for RedactedType2.redactedMethod in conformance RedactedType3 + 4313759640 (<compiler-generated>:4313759640)
14 MyApp                           0x1042b4e30 closure #1 in closure #1 in RedactedType1.redactedMethod + 305 (RedactedClass1.swift:305)
15 MyApp                           0x103261898 thunk for @escaping @callee_guaranteed () -> () + 4312389784 (<compiler-generated>:4312389784)
16 libdispatch.dylib              0x1969159a8 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x196916524 _dispatch_client_callout + 16
18 libdispatch.dylib              0x1968c28a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
19 libdispatch.dylib              0x1968c3294 _dispatch_lane_invoke$VARIANT$mp + 416
20 libdispatch.dylib              0x1968cc78c _dispatch_workloop_worker_thread + 588
21 libsystem_pthread.dylib        0x196967b74 _pthread_wqthread + 272
22 libsystem_pthread.dylib        0x19696a740 start_wqthread + 8
```
</details>

**Comment by xander-jones** [comment]
Hey @sethfri, looks like there could be an issue here. We'll take a look into it. If you do stumble across a method to reproduce this, please let us know.

**Comment by nickdowell** [comment]
This issue has been fixed in release [v6.2.3](https://github.com/bugsnag/bugsnag-cocoa/releases/tag/v6.2.3)

**Comment by sethfri** [comment]
@nickdowell @phillipsam We are still seeing around 100 instances of this crash when using Bugsnag 6.2.3. Could you please reopen this issue?

Here's the latest stack trace:

<details><summary>Stack trace:</summary>

```
Crashed: MyQueue
0  libobjc.A.dylib                0x19df16980 objc_retain + 16
1  CoreFoundation                 0x19e212ff0 __NSArrayI_new + 200
2  CoreFoundation                 0x19e0b34b4 -[NSArray initWithArray:range:copyItems:] + 412
3  CoreFoundation                 0x19e0b78f4 +[NSArray arrayWithArray:] + 72
4  MyApp                           0x101911354 -[BugsnagClient notify:handledState:block:] + 1055 (BugsnagClient.m:1055)
5  MyApp                           0x101910708 -[BugsnagClient notifyError:block:] + 934 (BugsnagClient.m:934)
6  MyApp                           0x101908750 +[Bugsnag notifyError:block:] + 147 (Bugsnag.m:147)
7  MyApp                           0x1024012f8 specialized BugsnagLogStoreWriter.write(level:message:parameters:) + 4329198328 (<compiler-generated>:4329198328)
8  MyApp                           0x1023f2de0 AggregateLogStoreWriter.write(level:message:parameters:) + 4329139680 (<compiler-generated>:4329139680)
9  MyApp                           0x1023f2ea0 protocol witness for LogStoreWriter.write(level:message:parameters:) in conformance AggregateLogStoreWriter + 4329139872 (<compiler-generated>:4329139872)
10 MyApp                           0x1023f9558 Logger.log(level:_:parameters:) + 4329166168 (<compiler-generated>:4329166168)
11 MyApp                           0x1022cfc1c closure #1 in Type1.personAutocompletionItems(forQuery:) + 4327947292 (<compiler-generated>:4327947292)
12 MyApp                           0x1025d0f10 Type2.uniqueAutocompletionItemsForSearchTerms(in:passingTest:) + 318 (Type2.swift:318)
13 MyApp                           0x1013480b4 protocol witness for AutocompleteResultsProvider.uniqueAutocompletionItemsForSearchTerms(in:passingTest:) in conformance Type2 + 4311662772 (<compiler-generated>:4311662772)
14 MyApp                           0x1022cf0d8 closure #1 in closure #1 in Type1.queryTypeaheadResults(withQuery:completionHandler:) + 305 (Type1.swift:305)
15 MyApp                           0x1011e9828 thunk for @escaping @callee_guaranteed () -> () + 4310226984 (<compiler-generated>:4310226984)
16 libdispatch.dylib              0x19de9e9a8 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x19de9f524 _dispatch_client_callout + 16
18 libdispatch.dylib              0x19de7cb3c _dispatch_lane_serial_drain$VARIANT$armv81 + 564
19 libdispatch.dylib              0x19de7d54c _dispatch_lane_invoke$VARIANT$armv81 + 396
20 libdispatch.dylib              0x19de8684c _dispatch_workloop_worker_thread + 580
21 libsystem_pthread.dylib        0x19def0b74 _pthread_wqthread + 272
22 libsystem_pthread.dylib        0x19def3740 start_wqthread + 8
```
</details>

**Comment by sethfri** [comment]
@johnkiely1 Pinging you here as well since you triaged the rest of the issues I just opened 🙏🏻

**Comment by nickdowell** [comment]
Hi @sethfri I can see a large number of events with this stack trace being reported to Bugsnag for version 3.26.3 of your app.

From the data we're receiving it looks like version 3.26.3 of your app uses Bugsnag v6.2.1, which does not include the recent improvements to breadcrumbs. Could you double check on your end whether you're definitely seeing this crash with Bugsnag v6.2.3?

**Comment by sethfri** [comment]
Ah terribly sorry, my mistake! That version of our app is indeed using Bugsnag 6.2.1. We haven't seen this in the version of our app using 6.2.3. Closing this again
